// constants.js
module.exports = {
  MESSAGES: {
    VALIDATION_ERROR: "Validation error",
    EMAIL_ALREADY_REGISTERED: "This email is already registered",
    VERIFY_EMAIL: "Please verify your email",
    SIGN_UP_AGAIN: "Please sign up again",
    INVALID_USER_OR_PASSWORD: "Invalid user or password",
    RESET_LINK_SENT: "Reset link has been sent to your registered email",
    EMAIL_NOT_FOUND: "Please send an email",
    UNAUTHORIZED_USER: "You are not authorized to perform this action",
    INVALID_OTP_OR_USER: "Invalid OTP or user not found",
    TOKEN_EXPIRED: "This link has expired",
    OLD_TOKEN: "This is an old token",
    NOT_LOGGED_IN: "You are not logged in, please login to get access",
    USER_NOT_EXIST: "This user does not exist",
    UPDATE_SUCCESS: " has been updated successfully",
    RESET_PASSWORD_SUCCESS: "You successfully changed your password",
    CHECK_EMAIL: "Check your email",
    EXPIRED_OTP: "Invalid OTP or user not found",
    EMAIL_VERIFICATION_REQUIRED: "Please verify your email",
    FAILED_EMAIL_SEND: "Failed to send email",
    INVALID_USER: "INVALID_USER",
    SEND_PASSWORD: "please send password",
    FORGOT_PASSWORD_GET_RESET_LINK: "FORGOT_PASSWORD_GET_RESET_LINK",
    PASSWORD: "PASSWORD",
    DOB: "dob ,",
    MOBILE: "mobile ,",
    NAME: "name ,",
    EMAILCONSTANT: "email ,",
    GENDER: "gender ,",
    ADDRESS: "ADRESS",
  },
  STATUS_CODES: {
    SUCCESS: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    INTERNAL_SERVER_ERROR: 500,
  },
  EMAIL: {
    SENDER: "feraz@gmail.com",
    SUBJECT: "Reset your password",
  },
  OTP_EXPIRY_DURATION: 10 * 60 * 1000, // 10 minutes in milliseconds
};
